Repository DanielGithumbi21/Positive-minds-frontend, pull requests merged in 2023-01, with the labels that each got.

#2 added the packages required for this application
  package-lock.json
  package.json
Labels: documentation, enhancement

#6 created the sidebar boilerplate
  index.html
  package-lock.json
  src/App.jsx
  src/Context/DataContext.jsx
  src/Routes/RoutesPage.jsx
  src/components/AppBar/AppBar.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/sideBarItems.js
  src/main.jsx
Labels: documentation, enhancement

#10 updated the routing architecture
  src/App.jsx
  src/Context/DataContext.jsx
  src/Routes/RoutesPage.jsx
  src/assets/image1.jpg
  src/components/Clients/Dashboard.jsx
  src/components/LandingPage/Icons.jsx
  src/components/LandingPage/LandingPage.jsx
  src/components/LandingPage/Navbar.jsx
  src/components/LandingPage/Results.jsx
  src/components/LandingPage/Tips.jsx
  src/components/LandingPage/Work.jsx
  src/components/Sidebar/Sidebar.css
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/sideBarItems.js
  src/main.jsx
Labels: bug, documentation, enhancement

#13 Creating login and signup screens
  src/App.jsx
  src/Context/DataContext.jsx
  src/components/Sign/Login.jsx
  src/components/Sign/SignUp.jsx
  src/index.css
  src/main.jsx
Labels: enhancement

#20 14 creating counsellor dashboard
  package.json
  src/App.jsx
  src/Context/DataContext.jsx
  src/Data/Auth/AuthHelper.jsx
  src/Data/Auth/Data.jsx
  src/components/AppBar/AppBar.jsx
  src/components/AppBar/Appbar.css
  src/components/Sign/Login.jsx
  src/components/Sign/SignUp.jsx
  src/index.css
Labels: bug

#17 admin dashboard environment setting
  index.html
  package-lock.json
  package.json
  src/Context/DataContext.jsx
  src/components/Admin/AdminDashboard.jsx
  src/components/Admin/AdminDashbord.css
Labels: enhancement

#24 created the client profile and dashboard
  src/Data/Auth/AuthHelper.jsx
  src/Data/Auth/Data.jsx
  src/Data/users/users.jsx
  src/Routes/RoutesPage.jsx
  src/assets/Rectangle.png
  src/assets/placeholder.jpg
  src/assets/ppp.png
  src/components/Clients/Dashboard.jsx
  src/components/Clients/Profile.css
  src/components/Clients/Profile.jsx
  src/components/Sidebar/sideBarItems.js
Labels: enhancement

#28 created private routes
  src/Routes/PrivateRoute.jsx
  src/Routes/RoutesPage.jsx
Labels: enhancement

#30 created counsellor's sidebar
  src/Routes/RoutesPage.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/sideBarItems.js
  src/components/counsellors/Dashboard.jsx
Labels: enhancement

#39 fixed responsiveness
  src/Context/DataContext.jsx
  src/Data/Auth/Data.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Sign/Login.jsx
Labels: bug

#40 37 admin data cards
  package-lock.json
  package.json
  src/App.jsx
  src/Data/Cards/AdminData.js
  src/components/Admin/AdminDashboard.jsx
  src/components/Admin/AdminDashbord.css
  src/components/Card/Card.css
  src/components/Card/Card.jsx
  src/components/Cards/Cards.css
  src/components/Cards/Cards.jsx
  src/components/MainDash/MainDash.css
  src/components/MainDash/MainDash.jsx
Labels: enhancement

#43 11 creating footer
  src/components/LandingPage/Footer.jsx
  src/components/LandingPage/Icons.jsx
  src/components/LandingPage/LandingPage.jsx
  src/components/LandingPage/Navbar.jsx
  src/components/LandingPage/Results.jsx
  src/components/LandingPage/Tips.jsx
  src/components/LandingPage/Work.jsx
Labels: enhancement

#45 cleaning the landing page
  src/components/LandingPage/Footer.jsx
  src/components/LandingPage/Icons.jsx
  src/components/LandingPage/LandingPage.jsx
  src/components/LandingPage/Navbar.jsx
  src/components/LandingPage/Work.jsx
  src/main.jsx
Labels: bug

#47 created sessions pages and apis
  package-lock.json
  package.json
  src/Context/DataContext.jsx
  src/Data/users/counsellors.jsx
  src/Routes/RoutesPage.jsx
  src/components/Sidebar/sideBarItems.js
  src/components/counsellors/CreateSession.jsx
  src/components/counsellors/Dashboard.jsx
  src/components/counsellors/SessionsDetails.jsx
  src/components/counsellors/ViewSessions.jsx
Labels: enhancement

#49 creating appointments
  src/Data/users/users.jsx
  src/Routes/RoutesPage.jsx
  src/components/Clients/Appointments.jsx
  src/components/Clients/BookAppointment.jsx
  src/components/Clients/Dashboard.jsx
  src/components/Sidebar/sideBarItems.js
Labels: enhancement

#54 created the admin sidebar
  package-lock.json
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/sideBarItems.js
  src/main.jsx
Labels: enhancement

#56 Progress
  src/components/Admin/AdminDashboard.jsx
  src/components/Admin/Card/Card.jsx
  src/components/Admin/Card/CardAdmin.css
  src/components/Admin/Cards/Cards.jsx
  src/components/Admin/CardsAdmin/AdminData.jsx
  src/components/Admin/CardsAdmin/CardsAdmin.jsx
  src/components/Admin/CardsAdmin/Cardsadmin.css
  src/components/Admin/MainDash/MainDash.css
  src/components/Admin/MainDash/MainDash.jsx
  src/components/Admin/Table/Table.css
  src/components/Admin/Table/Table.jsx
  src/main.jsx
Labels: enhancement

#58 card charts data display
  src/Routes/RoutesPage.jsx
  src/components/Admin/AdminDashboard.jsx
  src/components/Admin/AdminDashbord.css
  src/components/Admin/AdminData.jsx
  src/components/Admin/Card/Card.jsx
  src/components/Admin/Card/CardAdmin.css
  src/components/Admin/Cards/Cards.jsx
  src/components/Admin/CardsAdmin/AdminData.jsx
  src/components/Admin/CardsAdmin/CardsAdmin.jsx
  src/components/Admin/CardsAdmin/Cardsadmin.css
  src/components/Admin/Dashboard.css
  src/components/Admin/Dashboard.jsx
  src/components/Admin/MainDash/MainDash.css
  src/components/Admin/MainDash/MainDash.jsx
  src/components/Admin/Table/Table.jsx
Labels: enhancement

#60 55 getting counselor profile requests
  src/App.jsx
  src/Data/users/users.jsx
  src/Routes/RoutesPage.jsx
  src/components/Admin/CounsellorDetails.jsx
  src/components/Admin/CounsellorProfileRequests.jsx
  src/components/Clients/BeTherapist.jsx
  src/components/Clients/Dialog.jsx
  src/components/Sidebar/sideBarItems.js
Labels: enhancement

#59 42 handle client dashboards data
  package-lock.json
  src/Data/Auth/Data.jsx
  src/Data/Sessions/sessions.jsx
  src/components/Clients/Dashboard.jsx
Labels: bug

#63 booking appointment from session
  package-lock.json
  package.json
  src/Data/Auth/Data.jsx
  src/Data/users/counsellors.jsx
  src/Data/users/users.jsx
  src/components/Admin/AdminDashboard.jsx
  src/components/Admin/Card/Card.jsx
  src/components/Admin/Card/CardAdmin.css
  src/components/Admin/Cards/Cards.jsx
  src/components/Admin/CardsAdmin/CardsAdmin.jsx
  src/components/Admin/CardsAdmin/Cardsadmin.css
  src/components/Admin/MainDash/MainDash.css
  src/components/Admin/MainDash/MainDash.jsx
  src/components/Admin/Table/Table.css
  src/components/Admin/Table/Table.jsx
  src/components/Clients/BookAppointment.jsx
  src/components/Sidebar/sideBarItems.js
  src/components/counsellors/CreateSession.jsx
  src/components/counsellors/SessionsDetails.jsx
Labels: enhancement

#65 lazy loading and suspense loading
  src/Routes/RoutesPage.jsx
Labels: enhancement

#69 final changes
  src/Data/users/counsellors.jsx
  src/Data/users/users.jsx
  src/Routes/RoutesPage.jsx
  src/components/Admin/AdminDashboard.jsx
  src/components/Admin/CounsellorProfileRequests.jsx
  src/components/Clients/Profile.css
  src/components/Clients/Profile.jsx
  src/components/Clients/updateProfile.jsx
  src/components/Sidebar/sideBarItems.js
  src/components/counsellors/CounsellorAppointments.jsx
Labels: enhancement

#71 final changes
  src/Data/users/counsellors.jsx
  src/components/Clients/Profile.css
  src/components/counsellors/CounsellorAppointments.jsx
  src/components/counsellors/SessionsDetails.jsx
Labels: enhancement
